export const FETCH_RECOMMENDATIONS = "FETCH_RECOMMENDATIONS";
export const FETCH_TEASERS = "FETCH_TEASERS";
export const FETCH_PROFILE = "FETCH_PROFILE";
export const SWIPE_AND_NEXT = "SWIPE_AND_NEXT";
export const ADD_TO_LIKED_LIST = "ADD_TO_LIKED_LIST";
export const REMOVE_FROM_LIKED_LIST = "REMOVE_FROM_LIKED_LIST";
export const SWIPE_AND_RELOAD = "SWIPE_AND_RELOAD";