export const FETCH_RECOMMENDATIONS = "FETCH_RECOMMENDATIONS";
export const FETCH_TEASERS = "FETCH_TEASERS";
export const FETCH_PROFILE = "FETCH_PROFILE";
export const SWIPE_AND_NEXT = "SWIPE_AND_NEXT";